PUT http://localhost:3001/api/rates/65464478680f442c3ff41c8c HTTP/1.1
content-type: application/json

{
    "date": "2023-01-03T00:00:00.000Z",
    "baseRate": 13000,
    "adultRate": 500,
    "childRate": 300
}