POST http://localhost:3001/api/boats HTTP/1.1
content-type: application/json

{
  "numberOfBedrooms": 1,
  "boatType": "deluxe",
  "minAdultsRequired": 2,
  "defaultBaseRate": 6000,
  "defaultAdultRate": 500,
  "defaultChildRate": 300,
  "agency": "657ab25cd736bfe638723db1"
}