POST http://localhost:3001/api/boats HTTP/1.1
content-type: application/json

{
  "numberOfBedrooms": 2,
  "boatType": "deluxe",
  "minAdultsRequired": 2,
  "defaultBaseRate": 8000,
  "defaultAdultRate": 500,
  "defaultChildRate": 300,
  "agency": "657bf8cc3fdf820c121634b5"
}