PUT http://localhost:3001/api/boats/657ab3b5c970ef2d7bd57a4f HTTP/1.1
Content-Type: application/json

{
  "numberOfBedrooms": 1,
    "boatType": "deluxe",
    "minAdultsRequired": 2,
    "defaultBaseRate": 5400,
    "defaultAdultRate": 400,
    "defaultChildRate": 250,
    "defaultInfantRate": 0,
    "agency": "657ab25cd736bfe638723db1"  
}