PUT http://localhost:3001/api/availabilities/657ab63170440a5c28ecef4d HTTP/1.1
content-type: application/json

{
  "date": "2024-01-14T18:30:00.000Z",
  "isAvailable": true,
  "baseRate": 7500,
  "adultRate": 400,
  "childRate": 250
}